general {
    grab_focus = 1
}

cache {
    enabled = 1
}

ui {
    window_size = 600, 360
}

finders {
    default_finder = desktop
    desktop_icons = 1

    # Used to launch .desktop entries that declare Terminal=true
    desktop_terminal = ghostty

    # Prefix-switching: type one of these as the first character of the query
    # to switch finders mid-search.
    desktop_prefix =
    unicode_prefix = .
    math_prefix = =
    font_prefix = '
}
